version: '3.8'

networks:
  auth-network:
    driver: bridge
services:
  mydb:
    image: mysql:8.0
    container_name: auth-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASS
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - auth-network
volumes:
  temp-db: